### ISSUE TITLE
Linked to the same cheatsheet twice

### ISSUE THREAD

**Issue by manuelhaussmann** [AaltoSciComp/cheatsheets#1]
The cheatsheet overview seems to link to the same cheat sheet twice. 

https://github.com/AaltoSciComp/cheatsheets/blob/bd5ff45946b9da161f3691e68ef75c3307fbb4bb/index.html#L4-L5

Thanks for your work.

**Comment by rkdarst** [comment]
Thanks!  I just pushed something that should fix it.

It's been so long since we worked on these.  Are they still useful?
Would you recommend we improve and make more of these?

**Comment by manuelhaussmann** [comment]
Thanks. 
> It's been so long since we worked on these.  Are they still useful?

Assuming their information is still current, which it seems to be, they still feel useful. Of course that is after having just gone through the main documentation. Not sure how I will feel if I look at them in a couple of months as a refresher. 

> Would you recommend we improve and make more of these?

I currently don't think more are needed. One could argue that a nice Triton cheatsheet is missing, but the Triton quick reference and quickstart guide fulfill exactly the same purpose nicely, so it seems like a rather unnecessary duplication.

**Comment by manuelhaussmann** [comment]
Ignore my Triton comment. I just saw that there is indeed a Triton cheatsheet, it is just not linked in the `index.html`, but availble here in the repo and correctly linked to in the documentation.

**Comment by rkdarst** [comment]
Wow... I wonder if the duplicate link was me trying to add it, but
forgetting to edit it.  Well, thanks for pointing it out now... fixed.
