### ISSUE TITLE
Triton cheatsheet typo

### ISSUE THREAD

**Issue by manuelhaussmann** [AaltoSciComp/cheatsheets#2]
In the triton cheatsheet page 2, section batch jobs, second bullet point: 
> Example script at left 

Should be 

>Example script at **right**

_Edit: Same typo in the next section (Parallel jobs)_

Thanks for your work.

**Comment by rkdarst** [comment]
updated - thanks!  I hope if this is the level of revisions we have, I hope that means the rest is good.  Let us know if you find more that is wrong on unclear.
